"""
 comentÃ© turnos admin xq me daba este error
 TypeError: 'MediaDefiningClass' object is not iterable
PS C:\repositorios\clinica> python manage.py makemigrations
Traceback (most recent call last):
  File "C:\repositorios\clinica\manage.py", line 22, in <module>
    main()
  File "C:\repositorios\clinica\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 357, in execute
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\django\__init__.py", line 24, in setup    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\registry.py", line 122, in populate
    app_config.ready()
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\admin\apps.py", line 24, in ready
    self.module.autodiscover()
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\admin\__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\repositorios\clinica\turnos\admin.py", line 7, in <module>
    admin.site.register(TurnosAdmin, Turnos)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\admin\sites.py", line 102, in register
    for model in model_or_iterable:
TypeError: 'MediaDefiningClass' object is not iterable
"""

Quiero agregar una casilla de busqueda en la tabla y cuando lo hago de esta forma me 
sale el siguiente error:

from django.contrib import admin
from .models import*


class ProductosAdmin(admin.ModelAdmin):
    list_display=("nombre", "precio", "stock")
    search_fields=("nombre", "categorias")

admin.site.register(Categoria)
admin.site.register(Productos, ProductosAdmin )
admin.site.register(Pedidos)

FieldError at /admin/pedidos/productos/
Related Field got invalid lookup: icontains
Request Method:	GET
Request URL:	http://127.0.0.1:8000/admin/pedidos/productos/?q=pelota
Django Version:	2.2.4
Exception Type:	FieldError
Exception Value:	
Related Field got invalid lookup: icontains
Exception Location:	C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\sql\query.py in build_lookup, line 1107
Python Executable:	C:\Users\usuario\AppData\Local\Programs\Python\Python39\python.exe
Python Version:	3.9.5
Python Path:	
['C:\\repositorios\\clinica',
 'C:\\Users\\usuario\\AppData\\Local\\Programs\\Python\\Python39\\python39.zip',
 'C:\\Users\\usuario\\AppData\\Local\\Programs\\Python\\Python39\\DLLs',
 'C:\\Users\\usuario\\AppData\\Local\\Programs\\Python\\Python39\\lib',
 'C:\\Users\\usuario\\AppData\\Local\\Programs\\Python\\Python39',
 'C:\\Users\\usuario\\AppData\\Roaming\\Python\\Python39\\site-packages',
 'C:\\Users\\usuario\\AppData\\Roaming\\Python\\Python39\\site-packages\\win32',
 'C:\\Users\\usuario\\AppData\\Roaming\\Python\\Python39\\site-packages\\win32\\lib',
 'C:\\Users\\usuario\\AppData\\Roaming\\Python\\Python39\\site-packages\\Pythonwin',
 'C:\\Users\\usuario\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages']
Server time:	Sun, 8 Aug 2021 18:44:33 +0000
